INSERT INTO topics (public_id, subject_id, name, slug, description)
SELECT UUID(), s.id, t.name, t.slug, 'MVP topic'
FROM subjects s
JOIN (
    SELECT 'english-language' AS subject_slug, 'Comprehension' AS name, 'comprehension' AS slug
    UNION ALL SELECT 'english-language', 'Lexis and Structure', 'lexis-and-structure'
    UNION ALL SELECT 'english-language', 'Oral English', 'oral-english'
    UNION ALL SELECT 'english-language', 'Grammar', 'grammar'
    UNION ALL SELECT 'english-language', 'Parts of Speech', 'parts-of-speech'
    UNION ALL SELECT 'english-language', 'Sentence Structure', 'sentence-structure'
    UNION ALL SELECT 'english-language', 'Concord', 'concord'
    UNION ALL SELECT 'english-language', 'Tenses', 'tenses'
    UNION ALL SELECT 'english-language', 'Essay Writing', 'essay-writing'
    UNION ALL SELECT 'english-language', 'Letter Writing', 'letter-writing'
    UNION ALL SELECT 'english-language', 'Report Writing', 'report-writing'
    UNION ALL SELECT 'english-language', 'Summary Writing', 'summary-writing'
    UNION ALL SELECT 'mathematics', 'Number Bases', 'number-bases'
    UNION ALL SELECT 'mathematics', 'Algebra', 'algebra'
    UNION ALL SELECT 'mathematics', 'Indices and Logarithms', 'indices-and-logarithms'
    UNION ALL SELECT 'mathematics', 'Sets', 'sets'
    UNION ALL SELECT 'mathematics', 'Fractions and Percentages', 'fractions-and-percentages'
    UNION ALL SELECT 'mathematics', 'Equations and Inequalities', 'equations-and-inequalities'
    UNION ALL SELECT 'mathematics', 'Trigonometry', 'trigonometry'
    UNION ALL SELECT 'mathematics', 'Geometry', 'geometry'
    UNION ALL SELECT 'mathematics', 'Mensuration', 'mensuration'
    UNION ALL SELECT 'mathematics', 'Statistics', 'statistics'
    UNION ALL SELECT 'mathematics', 'Probability', 'probability'
    UNION ALL SELECT 'mathematics', 'Variation', 'variation'
    UNION ALL SELECT 'biology', 'Cell Biology', 'cell-biology'
    UNION ALL SELECT 'biology', 'Classification of Living Things', 'classification-of-living-things'
    UNION ALL SELECT 'biology', 'Ecology', 'ecology'
    UNION ALL SELECT 'biology', 'Genetics', 'genetics'
    UNION ALL SELECT 'biology', 'Reproduction', 'reproduction'
    UNION ALL SELECT 'biology', 'Nutrition', 'nutrition'
    UNION ALL SELECT 'biology', 'Respiration', 'respiration'
    UNION ALL SELECT 'biology', 'Excretion', 'excretion'
    UNION ALL SELECT 'biology', 'Growth and Development', 'growth-and-development'
    UNION ALL SELECT 'biology', 'Nervous System', 'nervous-system'
    UNION ALL SELECT 'biology', 'Evolution', 'evolution'
    UNION ALL SELECT 'biology', 'Human Physiology', 'human-physiology'
    UNION ALL SELECT 'chemistry', 'Atomic Structure', 'atomic-structure'
    UNION ALL SELECT 'chemistry', 'Chemical Bonding', 'chemical-bonding'
    UNION ALL SELECT 'chemistry', 'Periodic Table', 'periodic-table'
    UNION ALL SELECT 'chemistry', 'Stoichiometry', 'stoichiometry'
    UNION ALL SELECT 'chemistry', 'Acids and Bases', 'acids-and-bases'
    UNION ALL SELECT 'chemistry', 'Salts', 'salts'
    UNION ALL SELECT 'chemistry', 'Redox Reactions', 'redox-reactions'
    UNION ALL SELECT 'chemistry', 'Electrolysis', 'electrolysis'
    UNION ALL SELECT 'chemistry', 'Organic Chemistry', 'organic-chemistry'
    UNION ALL SELECT 'chemistry', 'Hydrocarbons', 'hydrocarbons'
    UNION ALL SELECT 'chemistry', 'Chemical Equilibrium', 'chemical-equilibrium'
    UNION ALL SELECT 'chemistry', 'Rates of Reaction', 'rates-of-reaction'
    UNION ALL SELECT 'physics', 'Measurement and Units', 'measurement-and-units'
    UNION ALL SELECT 'physics', 'Scalars and Vectors', 'scalars-and-vectors'
    UNION ALL SELECT 'physics', 'Motion', 'motion'
    UNION ALL SELECT 'physics', 'Forces', 'forces'
    UNION ALL SELECT 'physics', 'Work, Energy and Power', 'work-energy-and-power'
    UNION ALL SELECT 'physics', 'Heat Energy', 'heat-energy'
    UNION ALL SELECT 'physics', 'Waves', 'waves'
    UNION ALL SELECT 'physics', 'Light', 'light'
    UNION ALL SELECT 'physics', 'Sound', 'sound'
    UNION ALL SELECT 'physics', 'Electricity', 'electricity'
    UNION ALL SELECT 'physics', 'Magnetism', 'magnetism'
    UNION ALL SELECT 'physics', 'Modern Physics', 'modern-physics'
    UNION ALL SELECT 'economics', 'Basic Economic Concepts', 'basic-economic-concepts'
    UNION ALL SELECT 'economics', 'Demand', 'demand'
    UNION ALL SELECT 'economics', 'Supply', 'supply'
    UNION ALL SELECT 'economics', 'Price Determination', 'price-determination'
    UNION ALL SELECT 'economics', 'Production', 'production'
    UNION ALL SELECT 'economics', 'Market Structures', 'market-structures'
    UNION ALL SELECT 'economics', 'National Income', 'national-income'
    UNION ALL SELECT 'economics', 'Money and Banking', 'money-and-banking'
    UNION ALL SELECT 'economics', 'Inflation', 'inflation'
    UNION ALL SELECT 'economics', 'Public Finance', 'public-finance'
    UNION ALL SELECT 'economics', 'International Trade', 'international-trade'
    UNION ALL SELECT 'economics', 'Economic Development', 'economic-development'
    UNION ALL SELECT 'government', 'Meaning of Government', 'meaning-of-government'
    UNION ALL SELECT 'government', 'Constitution', 'constitution'
    UNION ALL SELECT 'government', 'Rule of Law', 'rule-of-law'
    UNION ALL SELECT 'government', 'Citizenship', 'citizenship'
    UNION ALL SELECT 'government', 'Political Parties', 'political-parties'
    UNION ALL SELECT 'government', 'Electoral Systems', 'electoral-systems'
    UNION ALL SELECT 'government', 'Legislature', 'legislature'
    UNION ALL SELECT 'government', 'Executive', 'executive'
    UNION ALL SELECT 'government', 'Judiciary', 'judiciary'
    UNION ALL SELECT 'government', 'Public Administration', 'public-administration'
    UNION ALL SELECT 'government', 'Local Government', 'local-government'
    UNION ALL SELECT 'government', 'International Organizations', 'international-organizations'
    UNION ALL SELECT 'literature-in-english', 'Poetry', 'poetry'
    UNION ALL SELECT 'literature-in-english', 'Drama', 'drama'
    UNION ALL SELECT 'literature-in-english', 'Prose', 'prose'
    UNION ALL SELECT 'literature-in-english', 'Literary Appreciation', 'literary-appreciation'
    UNION ALL SELECT 'literature-in-english', 'Figures of Speech', 'figures-of-speech'
    UNION ALL SELECT 'literature-in-english', 'Themes and Motifs', 'themes-and-motifs'
    UNION ALL SELECT 'literature-in-english', 'Characterization', 'characterization'
    UNION ALL SELECT 'literature-in-english', 'Plot Structure', 'plot-structure'
    UNION ALL SELECT 'literature-in-english', 'Setting', 'setting'
    UNION ALL SELECT 'literature-in-english', 'Tone and Mood', 'tone-and-mood'
    UNION ALL SELECT 'literature-in-english', 'African Literature', 'african-literature'
    UNION ALL SELECT 'literature-in-english', 'Literary Devices', 'literary-devices'
    UNION ALL SELECT 'geography', 'The Earth', 'the-earth'
    UNION ALL SELECT 'geography', 'Map Reading', 'map-reading'
    UNION ALL SELECT 'geography', 'Surveying', 'surveying'
    UNION ALL SELECT 'geography', 'Rocks', 'rocks'
    UNION ALL SELECT 'geography', 'Weather and Climate', 'weather-and-climate'
    UNION ALL SELECT 'geography', 'Vegetation', 'vegetation'
    UNION ALL SELECT 'geography', 'Soils', 'soils'
    UNION ALL SELECT 'geography', 'Population Geography', 'population-geography'
    UNION ALL SELECT 'geography', 'Settlement', 'settlement'
    UNION ALL SELECT 'geography', 'Transportation', 'transportation'
    UNION ALL SELECT 'geography', 'Industry', 'industry'
    UNION ALL SELECT 'geography', 'Environmental Conservation', 'environmental-conservation'
    UNION ALL SELECT 'accounting', 'Introduction to Accounting', 'introduction-to-accounting'
    UNION ALL SELECT 'accounting', 'Accounting Principles', 'accounting-principles'
    UNION ALL SELECT 'accounting', 'Double Entry System', 'double-entry-system'
    UNION ALL SELECT 'accounting', 'Cash Book', 'cash-book'
    UNION ALL SELECT 'accounting', 'Ledger Accounts', 'ledger-accounts'
    UNION ALL SELECT 'accounting', 'Trial Balance', 'trial-balance'
    UNION ALL SELECT 'accounting', 'Depreciation', 'depreciation'
    UNION ALL SELECT 'accounting', 'Bank Reconciliation', 'bank-reconciliation'
    UNION ALL SELECT 'accounting', 'Final Accounts', 'final-accounts'
    UNION ALL SELECT 'accounting', 'Control Accounts', 'control-accounts'
    UNION ALL SELECT 'accounting', 'Partnership Accounts', 'partnership-accounts'
    UNION ALL SELECT 'accounting', 'Company Accounts', 'company-accounts'
    UNION ALL SELECT 'commerce', 'Introduction to Commerce', 'introduction-to-commerce'
    UNION ALL SELECT 'commerce', 'Trade', 'trade'
    UNION ALL SELECT 'commerce', 'Retail Trade', 'retail-trade'
    UNION ALL SELECT 'commerce', 'Wholesale Trade', 'wholesale-trade'
    UNION ALL SELECT 'commerce', 'Advertising', 'advertising'
    UNION ALL SELECT 'commerce', 'Transportation', 'transportation'
    UNION ALL SELECT 'commerce', 'Warehousing', 'warehousing'
    UNION ALL SELECT 'commerce', 'Insurance', 'insurance'
    UNION ALL SELECT 'commerce', 'Banking', 'banking'
    UNION ALL SELECT 'commerce', 'Foreign Trade', 'foreign-trade'
    UNION ALL SELECT 'commerce', 'Business Units', 'business-units'
    UNION ALL SELECT 'commerce', 'Consumer Protection', 'consumer-protection'
    UNION ALL SELECT 'crs', 'Creation', 'creation'
    UNION ALL SELECT 'crs', 'The Patriarchs', 'the-patriarchs'
    UNION ALL SELECT 'crs', 'Leadership in Israel', 'leadership-in-israel'
    UNION ALL SELECT 'crs', 'The Prophets', 'the-prophets'
    UNION ALL SELECT 'crs', 'The Ten Commandments', 'the-ten-commandments'
    UNION ALL SELECT 'crs', 'Worship in Israel', 'worship-in-israel'
    UNION ALL SELECT 'crs', 'The Ministry of Jesus', 'the-ministry-of-jesus'
    UNION ALL SELECT 'crs', 'Miracles of Jesus', 'miracles-of-jesus'
    UNION ALL SELECT 'crs', 'Parables of Jesus', 'parables-of-jesus'
    UNION ALL SELECT 'crs', 'The Early Church', 'the-early-church'
    UNION ALL SELECT 'crs', 'Christian Living', 'christian-living'
    UNION ALL SELECT 'crs', 'Salvation and Faith', 'salvation-and-faith'
    UNION ALL SELECT 'irs', 'Articles of Faith', 'articles-of-faith'
    UNION ALL SELECT 'irs', 'Pillars of Islam', 'pillars-of-islam'
    UNION ALL SELECT 'irs', 'The Quran', 'the-quran'
    UNION ALL SELECT 'irs', 'Hadith', 'hadith'
    UNION ALL SELECT 'irs', 'Tawhid', 'tawhid'
    UNION ALL SELECT 'irs', 'Prophets in Islam', 'prophets-in-islam'
    UNION ALL SELECT 'irs', 'Life of Prophet Muhammad', 'life-of-prophet-muhammad'
    UNION ALL SELECT 'irs', 'Islamic Ethics', 'islamic-ethics'
    UNION ALL SELECT 'irs', 'Shariah', 'shariah'
    UNION ALL SELECT 'irs', 'Islamic Worship', 'islamic-worship'
    UNION ALL SELECT 'irs', 'Islamic Civilization', 'islamic-civilization'
    UNION ALL SELECT 'irs', 'Family Life in Islam', 'family-life-in-islam'
    UNION ALL SELECT 'agricultural-science', 'Introduction to Agriculture', 'introduction-to-agriculture'
    UNION ALL SELECT 'agricultural-science', 'Agricultural Ecology', 'agricultural-ecology'
    UNION ALL SELECT 'agricultural-science', 'Soil Science', 'soil-science'
    UNION ALL SELECT 'agricultural-science', 'Farm Tools and Equipment', 'farm-tools-and-equipment'
    UNION ALL SELECT 'agricultural-science', 'Crop Production', 'crop-production'
    UNION ALL SELECT 'agricultural-science', 'Animal Production', 'animal-production'
    UNION ALL SELECT 'agricultural-science', 'Agricultural Economics', 'agricultural-economics'
    UNION ALL SELECT 'agricultural-science', 'Farm Management', 'farm-management'
    UNION ALL SELECT 'agricultural-science', 'Agricultural Extension', 'agricultural-extension'
    UNION ALL SELECT 'agricultural-science', 'Forestry', 'forestry'
    UNION ALL SELECT 'agricultural-science', 'Fisheries', 'fisheries'
    UNION ALL SELECT 'agricultural-science', 'Agricultural Biotechnology', 'agricultural-biotechnology'
) t ON t.subject_slug = s.slug
WHERE NOT EXISTS (
    SELECT 1
    FROM topics existing_topic
    WHERE existing_topic.subject_id = s.id
      AND existing_topic.slug = t.slug
);
